language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

env:
  - QT_BASE=56

before_install:
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - sudo apt-get update -qq

install:
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base qt56script qt56tools ; source /opt/qt56/bin/qt56-env.sh; fi
  

script:
  - qmake -r limereport.pro
  - make
  - make check

notifications:
  email: false

